module.exports = {
    SET_MAP_CENTER: 'SET_MAP_CENTER',
    SET_AUTOCOMPLETE_VALUE: 'SET_AUTOCOMPLETE_VALUE',
    SET_ZOOM: 'SET_ZOOM',
    ADD_CUSTOM_MARKER: 'ADD_CUSTOM_MARKER',
    UPDATE_MARKER_VALUE: 'UPDATE_MARKER_VALUE',
}